# permissions for end users to view computes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: compute-viewer-role
rules:
- apiGroups:
  - cloudbuilder.example.com
  resources:
  - computes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloudbuilder.example.com
  resources:
  - computes/status
  verbs:
  - get
